export const AGREGAR_PREGUNTAS = "AGREGAR_PREGUNTAS";
export const AGREGAR_PREGUNTAS_ERROR = "AGREGAR_PREGUNTAS_ERROR";
export const AGREGAR_PREGUNTAS_EXITO = "AGREGAR_PREGUNTAS_EXITO";
export const COMENZAR_DESCARGA_PREGUNTAS = "COMENZAR_DESCARGA_PREGUNTAS";
export const OBETENER_PREGUNTAS_EXITO = "OBETENER_PREGUNTAS_EXITO";

